
image:
  repository: rraboy/stubby-helm
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 53

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

stubby_extra_yml: |
  resolution_type: GETDNS_RESOLUTION_STUB
  dns_transport_list:
    - GETDNS_TRANSPORT_TLS
  tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
  tls_query_padding_blocksize: 128
  edns_client_subnet_private : 1
  round_robin_upstreams: 1
  idle_timeout: 10000

  upstream_recursive_servers:
    ## Quad 9 'secure' service - Filters, does DNSSEC, doesn't send ECS
    - address_data: 9.9.9.9
      tls_auth_name: "dns.quad9.net"
    ## Quad 9 'insecure' service - No filtering, no DNSSEC, doesn't send ECS
    - address_data: 9.9.9.10
      tls_auth_name: "dns.quad9.net"
    ## Cloudflare 1.1.1.1 and 1.0.0.1
    ## (NOTE: recommend reducing idle_timeout to 9000 if using Coudflare)
    - address_data: 1.1.1.1
      tls_auth_name: "cloudflare-dns.com"
    - address_data: 1.0.0.1
      tls_auth_name: "cloudflare-dns.com"