apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stubby-helm.fullname" . }}
  labels:
    {{- include "stubby-helm.labels" . | nindent 4 }}
data:
  stubby.yml: |
    listen_addresses:
      - 0.0.0.0@53

    {{- .Values.stubby_extra_yml | nindent 4 }}