apiVersion: v1
kind: Service
metadata:
  name: {{ include "stubby-helm.fullname" . }}
  labels:
    {{- include "stubby-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.port }}
      targetPort: udp
      protocol: UDP
      name: udp
  selector:
    {{- include "stubby-helm.selectorLabels" . | nindent 4 }}
