name: build-chart

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'gcloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - run: |
          helm lint
          helm package .
          helm repo index --url https://storage.googleapis.com/github-rraboy-stubby-helm/ .

      - id: 'upload-helm-tgz'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'stubby-helm-0.1.0.tgz'
          destination: 'github-rraboy-stubby-helm/stubby-helm-0.1.0.tgz'
          
      - id: 'upload-index-yaml'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'index.yaml'
          destination: 'github-rraboy-stubby-helm/index.yaml'